# -*- coding: utf-8 -*-
"""luz,camera,analiseipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1QCZOnZZ_l7Yih10fcSaVbgxbFDLmB4
"""

import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

df = pd.read_csv('/content/base_de_filmes.csv' ,encoding='ISO-8859-1', delimiter=';')
df

df.head(5)

df.info()

df.isnull().sum()

df.shape

df.describe()

df.columns

df['Lucro (USD)'] = df['Receita (USD)'] - df['Orçamento (USD)']
df

print(df[['Título', 'Lucro (USD)']].head())

generos = df["Gênero"].value_counts()
generos

# Contagem de filmes por gênero
generos = df["Gênero"].value_counts().reset_index()
generos.columns = ["Gênero", "Quantidade"]

# Criando gráfico de barras estilizado
fig = px.bar(
    generos,
    x="Gênero",
    y="Quantidade",
    title="🎬 Distribuição de Filmes por Gênero",
    color="Gênero",
    text="Quantidade",
    color_discrete_sequence=px.colors.qualitative.Pastel
)

# Ajustes de layout
fig.update_layout(
    title_font_size=24,
    title_x=0.5,
    plot_bgcolor="#f9f9f9",
    paper_bgcolor="#f9f9f9",
    font=dict(size=14),
    showlegend=False
)

# Ajuste do texto nas barras
fig.update_traces(textposition="outside")

fig.show()

# Contagem de filmes lançados por ano
filmes_por_ano = df["Ano de Lançamento"].value_counts().reset_index()
filmes_por_ano.columns = ["Ano", "Quantidade"]
filmes_por_ano = filmes_por_ano.sort_values("Ano")

# Gráfico de linha estilizado
fig = px.line(
    filmes_por_ano,
    x="Ano",
    y="Quantidade",
    title="🎥 Evolução do Número de Filmes por Ano",
    markers=True,
    line_shape="spline"  # curva suave
)

# Estilo visual
fig.update_traces(line=dict(color="#636EFA", width=3), marker=dict(size=6, color="#EF553B"))
fig.update_layout(
    title_font_size=24,
    title_x=0.5,
    plot_bgcolor="#f9f9f9",
    paper_bgcolor="#f9f9f9",
    font=dict(size=14),
    xaxis_title="Ano",
    yaxis_title="Quantidade de Filmes"
)

fig.show()

df_top10 = df[:10]

# Gráfico de barras agrupadas estilizado
fig = px.bar(
    df_top10,
    x="Título",
    y=["Receita (USD)", "Orçamento (USD)"],
    title="💰 Comparação de Orçamento e Receita dos Filmes",
    labels={"value": "Valor em USD", "variable": "Categoria"},
    barmode="group",
    color_discrete_sequence=["#00CC96", "#636EFA"]
)

# Estilização extra
fig.update_layout(
    title_font_size=24,
    title_x=0.5,
    plot_bgcolor="#f9f9f9",
    paper_bgcolor="#f9f9f9",
    font=dict(size=14),
    xaxis_tickangle=-45,
    xaxis_title="Filmes",
    yaxis_title="Valor em USD",
    legend_title=""
)

# Borda arredondada nas barras (simulada com maior espaçamento)
fig.update_traces(marker_line_width=1.5, marker_line_color="white")

fig.show()